---
title: "Returrners_dataset"
author: "Z.CAI"
date: "2021年11月24日"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# The Returners DataSet

loading the returners dataset
```{r}
library(keras)

reuters <- dataset_reuters(num_words = 10000)
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% reuters
```
```{r}
length(train_data)
length(test_data)
```
```{r}
train_data[[1]]
```

decoding newswires back to text
```{r}
word_index <- dataset_reuters_word_index()
reverse_word_index <- names(word_index) 
names(reverse_word_index) <- word_index
decoded_newswire <- sapply(train_data[[1]], function(index) {
  word <- if (index >= 3) reverse_word_index[[as.character(index - 3)]]
  if (!is.null(word)) word else "?" 
  })

decoded_newswire
```
```{r}
train_labels[[1]]
```
encoding the data
```{r}
vectorize_sequences <- function(sequences, dimension = 10000) { 
  results <- matrix(0, nrow = length(sequences), ncol = dimension) 
  for (i in 1:length(sequences))
    results[i, sequences[[i]]] <- 1 
  results
}

x_train <- vectorize_sequences(train_data) 
x_test <- vectorize_sequences(test_data)

str(x_train)
str(x_test)
```
```{r}
to_one_hot <- function(labels, dimension = 46) {
  results <- matrix(0, nrow = length(labels), ncol = dimension) 
  for (i in 1:length(labels))
    results[i, labels[[i]] + 1] <- 1
  results
}

one_hot_train_labels <- to_one_hot(train_labels)
one_hot_test_labels <- to_one_hot(test_labels)

str(one_hot_train_labels)
str(one_hot_test_labels)
```
model definition
```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu", input_shape = c(10000)) %>% 
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 46, activation = "softmax")
    
```

compiling the model
```{r}
model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy", 
  metrics = c("accuracy")
)
```

setting aside a validation set
```{r}
val_indices <- 1:1000

x_val <- x_train[val_indices,] 
partial_x_train <- x_train[-val_indices,]

y_val <- one_hot_train_labels[val_indices,] 
partial_y_train = one_hot_train_labels[-val_indices,]
```

training the model
```{r}
history <- model %>% fit(
  partial_x_train, 
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)
```
plotting the training and validation metrics
```{r}
plot(history)
```

retrainin a model from scratch
```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu", input_shape = c(10000)) %>% 
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 46, activation = "softmax")

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy", 
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train, 
  partial_y_train,
  epochs = 9,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)

results <- model %>% evaluate(x_test, one_hot_test_labels)
results
```
compare a random baseline
```{r}
test_labels_copy <- test_labels
test_labels_copy <- sample(test_labels_copy)
length(which(test_labels == test_labels_copy)) / length(test_labels)
```
generate predictions for new data
```{r}
predictions <- model %>% predict(x_test)

dim(predictions)
sum(predictions[1,])
which.max(predictions[1,])
```
