---
title: "minst"
author: "Z.CAI"
date: "2021年11月9日"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("C:/Users/CAI/Desktop/Deep_Learning_with_R/MINST/MINST_example")
```


# The MNIST Data Example 

```{r}
library(keras)

mnist <- dataset_mnist()
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images <- mnist$test$x
test_labels <- mnist$test$y
```

# glimpse the structure of array using str() function

```{r}
str(train_images)
str(train_labels)
str(test_images)
str(test_labels)
```

# the network architecture

```{r}
network <- keras_model_sequential() %>%
  layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
  layer_dense(units = 10, activation = "softmax")
```

# the compilation step

```{r}
network %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)
```

# preparing the image data

```{r}
train_images <- array_reshape(train_images, c(60000, 28 * 28))
train_images <- train_images / 255

test_images <- array_reshape(test_images, c(10000, 28 * 28))
test_images <- test_images / 255
```

# preparing the labels

```{r}
train_labels <- to_categorical(train_labels)
test_labels <- to_categorical(test_labels)
```

# train the network (keras network's fit method)

```{r}
network %>% fit(
  train_images,
  train_labels,
  epochs = 5, 
  batch_size = 128
)
```












